### ISSUE TITLE
Husky can't find dependency in generated js file

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/eclipse-tractusx.github.io#262]
When trying to commit a change, the husky pre-commit job crashes. `npm run lint-doc` executed manually finishes without errors. Do you have any idea why this may be?
```
17:09:23.389: [eclipse-tractusx.github.io] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false rm --ignore-unmatch --cached -r -- openApi/dt/discovery-finder.yaml "docs/kits/Digital Twin Kit/page_documentation.md" "docs/kits/Digital Twin Kit/Software Development View/page_software-development-view.md" "docs/kits/Digital Twin Kit/page_adoption-view.md" openApi/dt/edc-discovery.yaml openApi/dt/bpn-discovery.yaml "docs/kits/Digital Twin Kit/page_software-operation-view.md" docs/products/sldt.md
17:09:23.461: [eclipse-tractusx.github.io] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- docusaurus.config.js "docs/kits/Discovery Kit/Software Development View/BPN Discovery API/bpn-discovery-service.info.mdx" "docs/kits/Discovery Kit/Software Development View/page_software-development-view.md" openApi/discovery/edc-discovery.json openApi/discovery/discovery-finder-openapi.yaml "docs/kits/Discovery Kit/Software Development View/EDC Discovery API/sidebar.js" "docs/kits/Discovery Kit/Software Development View/BPN Discovery API/delete-bpn-discovery-by-id.api.mdx" "docs/kits/Discovery Kit/Software Development View/Discovery Finder API/delete-discovery-endpoint-by-resource-id.api.mdx" "docs/kits/Discovery Kit/Software Development View/Discovery Finder API/sidebar.js" "docs/kits/Discovery Kit/Software Development View/Discovery Finder API/get-discovery-endpoints.api.mdx" "docs/kits/Discovery Kit/Software Development View/Discovery Finder API/post-discovery-endpoint.api.mdx" "docs/kits/Discovery Kit/page_software-operation-view.md" "docs/kits/Discovery Kit/Software Development View/EDC Discovery API/retrieve-company-connector-end-point-with-bpn-authorization-required-roles-view-connectors.api.mdx" "docs/kits/Discovery Kit/Software Development View/Discovery Finder API/discovery-finder.info.mdx" "docs/kits/Discovery Kit/Software Development View/BPN Discovery API/post-bpn-discovery.api.mdx" sidebars.js "docs/kits/Discovery Kit/page_documentation.md" "docs/kits/Discovery Kit/Software Development View/EDC Discovery API/updates-the-connector-url-authorization-required-roles-modify-connectors.api.mdx" "docs/kits/Discovery Kit/Software Development View/BPN Discovery API/get-bpn-discoveries.api.mdx" "docs/kits/Discovery Kit/Software Development View/BPN Discovery API/post-batch-bpn-discovery.api.mdx" "docs/kits/Discovery Kit/Software Development View/BPN Discovery API/sidebar.js" openApi/discovery/bpn-discovery-service-openapi.yaml "docs/kits/Discovery Kit/page_adoption-view.md"
17:09:23.507: [eclipse-tractusx.github.io] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F /tmp/git-commit-msg-.txt --
> eclipse-tractusx-github-io@0.0.0 lint-doc
> markdownlint-cli2-config .markdownlint.yaml "docs/**/*.md" "#node_modules"
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module 'node:path'
Require stack:
- /home/arno/IdeaProjects/eclipse-tractusx.github.io/node_modules/markdownlint-cli2/markdownlint-cli2.js
- /home/arno/IdeaProjects/eclipse-tractusx.github.io/node_modules/markdownlint-cli2/markdownlint-cli2-config.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/arno/IdeaProjects/eclipse-tractusx.github.io/node_modules/markdownlint-cli2/markdownlint-cli2.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/arno/IdeaProjects/eclipse-tractusx.github.io/node_modules/markdownlint-cli2/markdownlint-cli2.js',
    '/home/arno/IdeaProjects/eclipse-tractusx.github.io/node_modules/markdownlint-cli2/markdownlint-cli2-config.js'
  ]
}
husky - pre-commit hook exited with code 1 (error)
```

**Comment by arnoweiss** [comment]
@Siegfriedk - do you have an idea or know somebody who could know?

**Comment by Siegfriedk** [comment]
@arnoweiss nope no clue. You can check what the pre-commit hook is doing as its configured in the repo as far as i know. But it might be an issue with your node.js version. But i'm not a good candidate to debug this

**Comment by arnoweiss** [comment]
Likely the intellij-git-integration caused this, committing via terminal runs smoothly.
